name: Setup
description: Installs Node, Enables Corepack and caches pnpm.

runs:
  using: composite

  steps:
    - name: Use Latest Corepack
      run: |
        echo "Before: corepack version => $(corepack --version || echo 'not installed')"
        npm install -g corepack@latest
        echo "After : corepack version => $(corepack --version)"
        corepack enable
        pnpm --version
      shell: bash

    - name: Setup node & pnpm
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
