name = "shadcn-vue-www"
compatibility_date = "2024-01-15"

# Build output directory (VitePress default)
pages_build_output_dir = ".vitepress/dist"

[env.production]
name = "shadcn-vue-www"

[env.preview]
name = "shadcn-vue-www-preview"

# Environment variables
[env.production.vars]
NODE_ENV = "production"
VITE_APP_ENV = "production"

[env.preview.vars]
NODE_ENV = "development"
VITE_APP_ENV = "preview"
