name = "shadcn-vue-www"
compatibility_date = "2024-01-15"

# Build output directory (VitePress default)
pages_build_output_dir = ".vitepress/dist"

# Build command
build_command = "pnpm build"

# Root directory
root_dir = "."

# Node.js version
node_version = "18"

[env.production]
name = "shadcn-vue-www"
route = "www.shadcn-vue.com/*"

[env.preview]
name = "shadcn-vue-www-preview"

# Environment variables
[env.production.vars]
NODE_ENV = "production"
VITE_APP_ENV = "production"

[env.preview.vars]
NODE_ENV = "development"
VITE_APP_ENV = "preview"
